help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

install: ## Install dependencies
	npm install

dev: ## Run the dev server
	npm run dev

build: ## Build for production
	npm run build

preview: ## Preview the production build
	npm run preview

clean: ## Clean autogenerated files
	rm -rf dist
	rm -rf node_modules
